Feature/md 5295 correctly check all feature commits
moneymeets/action-merge-checks pull request #4
Opened 2021-04-28 13:49 UTC by felix11h

## Reviewer

- [ ] for your information @marns93 @pchorus  
- [ ] process and function, acceptance criteria
- [ ] implementation (code design, correctness, formatting) @zyv 
- [ ] testing 

## Description

Fixes MD-5295 and implements @zyv's comments on https://github.com/moneymeets/action-merge-checks/pull/3#pullrequestreview-645694315.

2021-04-28 13:55 UTC, zyv requested changes

2021-04-28 13:55 UTC, zyv commented on merge_checks.py
> +    subprocess.run(f"git fetch --unshallow origin {base_ref}", check=True, shell=True)
Aus Performanz-Gründen würde ich es anderes machen, und zwar hier es wirklich so als fast-path lassen, und dann hinter `print("Getting commit list...")` folgendes reinstecken:

```python
subprocess.run("git fetch --unshallow", check=True, shell=True)
```

2021-04-28 13:55 UTC, zyv commented on merge_checks.py
> +    return 0
👍

2021-04-29 04:56 UTC, felix11h commented on merge_checks.py
> +    subprocess.run(f"git fetch --unshallow origin {base_ref}", check=True, shell=True)
Ah, ich glaube ich kann dein Argument verstehen. Habe ich geändert und auch noch einmal getestet, df1e0dfb0579ebdcc61aaf3f0899be80b2ddcaa4.

2021-04-29 06:42 UTC, zyv commented on merge_checks.py
> +    commits, subject_markers, _ = zip(*(line.decode().split(maxsplit=2) for line in log.stdout.splitlines()))
Ich habe es damals anders geschrieben, weil ich wollte nicht, dass es einfach crasht, wenn ich sowas wie `fixup!` committen, und gleichzeitig wollte ich auch nicht das Zeug mit exception handling verkomplizieren. Sind meine Sorgen an der Stelle unbegründet?

2021-04-29 07:53 UTC, stohrendorf commented
Änderungen wie mit @felix11h besprochen umgesetzt, sprich Tests und korrektere Prüfung auf Squashes/Fixups wurden umgesetzt.

2021-04-29 15:21 UTC, felix11h commented
> Änderungen wie mit @felix11h besprochen umgesetzt, sprich Tests und korrektere Prüfung auf Squashes/Fixups wurden umgesetzt.

Vielen Dank für die Tests, @stohrendorf! Ich habe die Datei mit den Tests umbenannt und einen Typo gefixed, siehe 58d6ecf2b2a518d4e78d98291715645e4b4dd82e. So für dich ok?

Logisch konnte ich die Tests nachvollziehen, ob man es noch besser struktieren schreiben kann ich leider nicht beurteilen. Hier wurde nun pytest verwendet, an anderen Stellen benutzen wir nose. Gibt es dazu eigentlich schon eine einheitliche Meinung?

2021-04-29 19:12 UTC, stohrendorf commented
a) nose wird nicht mehr fortgeführt, daher pytest. Die anderen Projekte sollten eigentlich mal darauf umgestellt werden.
b) den Typo im Dateinamen hab ich nicht gesehen, danke, ebensowenig wie den Typo in den Testdaten.
c) wie gesagt, bei den Tests an sich bin ich nicht 100% zufrieden wie das gebaut ist. Ich hätte da zwar eine Idee, wie es anders gehen _könnte_, aber gewonnen wäre dadurch dann nicht unbedingt was.

2021-04-30 07:39 UTC, zyv commented on test_merge_checks.py
> +                patch_has_merge_commits(False) as has_merge_commits_mock:
Ich finde es super, dass es jetzt auch hier Tests gibt. Ich hätte allerdings die patches womöglich auf Classen- und Methoden-ebenen gezogen, siehe z.B. hier:

https://github.com/moneymeets/action-heroku-deploy/blob/master/test_deploy_heroku.py

Ich glaube, dass es sieht viel übersichtlicher aus, du sparst Indentation-levels und man braucht ggfs. nicht die rausgezogene Funktionen...

2021-04-30 09:37 UTC, zyv commented on test_merge_checks.py
> +                patch_has_merge_commits(False) as has_merge_commits_mock:
@felix11h @stohrendorf könnt ihr bitte dafür ein Folgeticket noch öffnen?

2021-04-30 09:37 UTC, zyv approved these changes

2021-04-30 09:56 UTC, felix11h commented on test_merge_checks.py
> +                patch_has_merge_commits(False) as has_merge_commits_mock:
Ticket schon einmal hier angelegt, https://moneymeets.atlassian.net/browse/MD-5312. Werde ich dann heute Nachmittag noch mit Inhalt füllen.

2021-04-30 09:59 UTC, merged